version: '3.8'
services:
  database:
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: tecdan
    volumes:
      - db-data:/var/lib/mysql  
    ports:
      - '3306:3306'  
    networks:
      dev:  

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - "8741:8741"
    environment:
      PMA_HOST: database

  www:
    image: tecdan-image:latest
    ports:
      - "8080:80"
    restart: always
    networks:
      dev:
    # environment:
    #   DATABASE_URL="mysql://root:@127.0.0.1:3306/tecdan?serverVersion=10.11.2-MariaDB&charset=utf8mb4"

networks:
  dev:

volumes:
  db-data:
